services:
  api:
    build: .
    container_name: vehicle_api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DSN=postgresql://user:password@db:5432/mydatabase
      - S3_BUCKET=vehicles
      - S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - YOLO_VEHICLE_MODEL=/app/datasets/models/yolov8l.pt
      - YOLO_DAMAGE_MODEL=/app/datasets/models/yolo_damage.pt
      - PROCESS_PORT=8000
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - USE_LOCALSTACK=true
    depends_on:
      - db
      - minio
      - localstack
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/data/postgres
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data/minio --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./data:/data
    restart: unless-stopped

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./data/localstack:/data/localstack
    restart: unless-stopped