services:
  lpr:
    build: .
    container_name: python_app
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - VIDEO_SOURCE=0     # Webcam padrão, pode substituir por RTSP/HTTP
    volumes:
      - .:/app
    restart: unless-stopped